FROM golang:latest

COPY . /go/src/kanggo/mapService/

WORKDIR /go/src/kanggo/mapService/

ENV MONGODB_URL=""
ENV SERVER_PORT=""
ENV GOOGLE_API_KEY=""

RUN go get -d -v go.mongodb.org/mongo-driver/mongo \
    && go get -d -v github.com/gorilla/mux \
    && go get -d -v github.com/gorilla/handlers \
    && go get googlemaps.github.io/maps

EXPOSE 8093

RUN go build -o main main.go

RUN ls -la

CMD ["./main"]